### ISSUE TITLE
unable to pull

### ISSUE THREAD

**Issue by ThomasVermeersch** [TiboDeClercq/Afstudeerproject#39]
@app.route('/downloadzip', methods=["POST"])
def downloadzip():
    report_id = request.form.get("report_id")
    tasks.zip_files(report_id)
    path= "../zipfiles/" + tasks.get_target_name[0:-20] + ".zip"
    return send_file(path)

def zip_files(report_id):
	full_target_name=get_target_name(report_id)
	target_name=get_target_name(report_id)[:-20]
	path = "txtfiles/answers_target_" + target_name
	reportpath = "reportdownload/" + report_id + ".csv"

	try:
		os.system("mkdir zipfiles")
	except:
		print("directory exists")

	zipObj = ZipFile("zipfiles/"+target_name+'.zip', 'w')
	zipObj.write(path)
	zipObj.write(reportpath)
	zipObj.close()
	print("successfull zipped")

def get_target_name(report_id):
	with Gmp(connection, transform=transform) as gmp:
		gmp.authenticate(user, password)
		xml = gmp.get_report(report_id)
		l = get_name(xml)
		return l[-1]

<td>
                        <form action="/downloadzip" method="POST">
                            <input type="hidden" name="report_id" value="{{task.report_id}}">
                            <input class="btn btn-outline-primary" type="submit" value="Zip">
                        </form>
                    </td>

**Comment by ThomasVermeersch** [comment]
<td>
                        <form action="/downloadzip" method="POST">
                            <input type="hidden" name="report_id" value="{{task.report_id}}">
                            <input class="btn btn-outline-primary" type="submit" value="Zip">
                        </form>
                    </td>

**Comment by ThomasVermeersch** [comment]
<form action="/downloadzip" method="POST">
                            <input type="hidden" name="report_id" value="{{task.report_id}}">
                            <input class="btn btn-outline-primary" type="submit" value="Zip">
</form>
                    </td>

**Comment by TiboDeClercq** [comment]
LAAT MIJ GERUST
________________________________
Van: ThomasVermeersch <notifications@github.com>
Verzonden: woensdag 7 oktober 2020 14:24
Aan: TiboDeClercq/Afstudeerproject <Afstudeerproject@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [TiboDeClercq/Afstudeerproject] unable to pull (#39)
